apiVersion: v1
kind: Service
metadata:
  name: fedops-web-backend-service
spec:
  selector:
    app: fedops-web-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
