apiVersion: v1
kind: Service
metadata:
  name: fedops-web-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: fedops-web-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
